# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Cristiano.Chrono
PackageVersion: 2.0.0
MinimumOSVersion: 10.0.17763.0
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/cristianobleve/chrono/releases/download/v2.0.0/Chrono_2.0.0_x64-setup.exe
  InstallerSha256: 48D799954840C9B6E0C2641A638A10F06287CCC071993039E5954ADA68B01C7E
  ProductCode: com.cristianobleve.chrono
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-10-05
